export const ProgramSchema = {
  appProperty: { key: 'createdBy', value: 'ikkos' },
  columns: {
    date: { index: 0, column: 'A' },
    week: { index: 1, column: 'B' },
    workout: { index: 2, column: 'C' },
    exercise: { index: 3, column: 'D' },
    set: { index: 4, column: 'E' },
    targetReps: { index: 5, column: 'F' },
    rir: { index: 6, column: 'G' },
    weight: { index: 7, column: 'H' },
    repsAchieved: { index: 8, column: 'I' },
    rirAchieved: { index: 9, column: 'J' },
    notes: { index: 10, column: 'K' },
    targetRestTime: { index: 11, column: 'L' },
    achievedRestTime: { index: 12, column: 'M' },
  },
  headers: [
    'Date',
    'Week',
    'Workout',
    'Exercise',
    'Set',
    'Target Reps',
    'RIR',
    'Weight',
    'Reps Achieved',
    'RIR Achieved',
    'Notes',
    'Target Rest',
    'Rest Time',
  ],
} as const;
